const hamburger=document.getElementById('hamburger');const navLinks=document.getElementById('navLinks');if(hamburger){hamburger.addEventListener('click',()=>{hamburger.classList.toggle('active');navLinks.classList.toggle('active');});document.querySelectorAll('.nav-links a').forEach(link=>{link.addEventListener('click',()=>{hamburger.classList.remove('active');navLinks.classList.remove('active');});});}
const contactForm=document.getElementById('contactForm');if(contactForm){let pendingSubmission=false;let formData={};const showFieldError=(fieldId,message)=>{const errorDiv=document.getElementById(`${fieldId}Error`);if(errorDiv){errorDiv.textContent=message;errorDiv.classList.add('show');}};const hideFieldError=(fieldId)=>{const errorDiv=document.getElementById(`${fieldId}Error`);if(errorDiv){errorDiv.classList.remove('show');}};const hideAllErrors=()=>{const fields=['name','email','phone','location','age','service'];fields.forEach(field=>hideFieldError(field));};const showMessage=(type,text)=>{const formMessage=document.getElementById('formMessage');formMessage.className=`form-message ${type}`;formMessage.textContent=text;formMessage.style.display='block';};const showConfirmation=()=>{const formMessage=document.getElementById('formMessage');formMessage.className='form-message warning';formMessage.innerHTML=`<div class="confirmation-box"><p>⚠️ هل أنت متأكد أنك لا تريد تزويدنا بتفاصيل إضافية عن حجزك؟</p><p>ننصح بتعبئة حقل الرسالة لمساعدتنا في تلبية احتياجات كلبك بشكل أفضل.</p><button class="confirm-btn" id="confirmSend">نعم، متأكد - أرسل الطلب</button><button class="cancel-btn" id="cancelConfirm">لا، سأكتب التفاصيل</button></div>`;formMessage.style.display='block';document.getElementById('confirmSend').addEventListener('click',function(){submitForm(formData,true);});document.getElementById('cancelConfirm').addEventListener('click',function(){formMessage.style.display='none';document.getElementById('message').focus();});};const submitForm=(data,confirmed=false)=>{let successMessage='';if(data.service.includes('مميزة')){successMessage='✅ تم استلام طلب الحزمة المميزة بنجاح! فريق Loving Homes في هونج كونج - الصين سيتواصل معك قريباً.';}else if(data.service.includes('كلاسيكية')){successMessage='✅ تم استلام طلب الحزمة الكلاسيكية بنجاح! فريق Loving Homes في هونج كونج - الصين سيتواصل معك قريباً.';}else if(data.service.includes('اليوم الواحد')){successMessage='✅ تم استلام طلب حزمة اليوم الواحد بنجاح! فريق Loving Homes في هونج كونج - الصين سيتواصل معك قريباً.';}else if(data.service.includes('مخصصة')){successMessage='✅ تم استلام طلب الحزمة المخصصة بنجاح! فريق Loving Homes في هونج كونج - الصين سيتواصل معك قريباً لمناقشة التفاصيل.';}else{successMessage='✅ تم إرسال طلبك بنجاح! فريق Loving Homes في هونج كونج - الصين سيتواصل معك قريباً.';}
showMessage('success',successMessage);contactForm.reset();pendingSubmission=false;formData={};setTimeout(()=>{document.getElementById('formMessage').style.display='none';},6000);};const phoneInput=document.getElementById('phone');if(phoneInput){phoneInput.addEventListener('keypress',function(e){const char=String.fromCharCode(e.which);if(!/[0-9+]/.test(char)){e.preventDefault();}if(char==='+'&&this.value.includes('+')){e.preventDefault();}});}const ageInput=document.getElementById('age');if(ageInput){ageInput.addEventListener('keypress',function(e){if(!/[0-9]/.test(e.key)){e.preventDefault();}});}
contactForm.addEventListener('submit',function(e){e.preventDefault();hideAllErrors();const name=document.getElementById('name')?.value.trim();const email=document.getElementById('email')?.value.trim();const phone=document.getElementById('phone')?.value.trim();const location=document.getElementById('location')?.value.trim();const age=document.getElementById('age')?.value;const service=document.getElementById('service')?.value;const message=document.getElementById('message')?.value.trim();const formMessage=document.getElementById('formMessage');let hasError=false;if(!name){showFieldError('name','الاسم مطلوب');hasError=true;}const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!email){showFieldError('email','البريد الإلكتروني مطلوب');hasError=true;}else if(!emailPattern.test(email)){showFieldError('email','البريد الإلكتروني غير صحيح');hasError=true;}
if(!phone){showFieldError('phone','رقم الهاتف مطلوب');hasError=true;}else{const phonePattern=/^\+?[0-9]+$/;if(!phonePattern.test(phone)){showFieldError('phone','رقم الهاتف يجب أن يحتوي على أرقام فقط، ويمكن أن يبدأ بـ +');hasError=true;}}
if(!location){showFieldError('location','مكان السكن مطلوب');hasError=true;}
if(!age){showFieldError('age','عمر الكلب مطلوب');hasError=true;}else if(isNaN(age)||age<1||age>100){showFieldError('age','عمر الكلب يجب أن يكون رقماً بين 1 و 100');hasError=true;}
if(!service){showFieldError('service','نوع الخدمة مطلوب');hasError=true;}
if(hasError)return;if(service==='حزمة مخصصة (إقامة طويلة)'&&!message){showMessage('error','❌ للحزم المخصصة، يجب كتابة تفاصيل طلبك في حقل الرسالة.');return;}
formData={name,email,phone,location,age,service,message};if(!message&&service!=='حزمة مخصصة (إقامة طويلة)'){showConfirmation();return;}
submitForm(formData);});const serviceSelect=document.getElementById('service');const messageField=document.getElementById('message');const formMessage=document.getElementById('formMessage');if(serviceSelect&&messageField){serviceSelect.addEventListener('change',function(){if(this.value==='حزمة مخصصة (إقامة طويلة)'){messageField.placeholder='⚠️ إجباري: اكتب تفاصيل الإقامة المطلوبة والمدة...';messageField.style.borderColor='var(--gold)';messageField.style.borderWidth='2px';showMessage('info','📝 للحزم المخصصة، يرجى كتابة تفاصيل الإقامة المطلوبة (المدة، الخدمات الإضافية، أي متطلبات خاصة)');}else{messageField.placeholder='اكتب أي تفاصيل إضافية عن طلبك (اختياري)';messageField.style.borderColor='#e0d6c8';messageField.style.borderWidth='1.5px';formMessage.style.display='none';}});}}
const modal=document.getElementById('imageModal');if(modal){const modalImg=document.getElementById('modalImage');const captionText=document.getElementById('caption');window.openModal=function(element){const img=element.querySelector('img');modal.style.display='flex';modalImg.src=img.src;captionText.innerHTML=img.alt;document.body.style.overflow='hidden';};window.closeModal=function(){modal.style.display='none';document.body.style.overflow='auto';};window.closeModalOnClick=function(event){if(event.target===modal){closeModal();}};document.addEventListener('keydown',function(e){if(e.key==='Escape'&&modal.style.display==='flex'){closeModal();}});}
const accessToggle=document.getElementById('accessToggle');const accessPanel=document.getElementById('accessPanel');let hideTimeout;if(accessToggle&&accessPanel){accessToggle.addEventListener('click',function(e){e.stopPropagation();accessPanel.classList.toggle('show');if(accessPanel.classList.contains('show')){clearTimeout(hideTimeout);}});accessPanel.addEventListener('click',function(e){e.stopPropagation();});document.addEventListener('click',function(e){if(accessPanel.classList.contains('show')&&!accessToggle.contains(e.target)&&!accessPanel.contains(e.target)){hideTimeout=setTimeout(()=>{accessPanel.classList.remove('show');},3000);}});accessPanel.addEventListener('mouseenter',function(){clearTimeout(hideTimeout);});accessPanel.addEventListener('mouseleave',function(){if(accessPanel.classList.contains('show')){clearTimeout(hideTimeout);hideTimeout=setTimeout(()=>{accessPanel.classList.remove('show');},3000);}});}
let currentZoom=parseInt(localStorage.getItem('zoomLevel'))||2;function setZoom(level){const html=document.documentElement;const sizes=[14,16,18,20,22];html.style.fontSize=sizes[level-1]+'px';localStorage.setItem('zoomLevel',level);for(let i=1;i<=5;i++){document.body.classList.remove(`zoom-${i}`);}document.body.classList.add(`zoom-${level}`);}
setZoom(currentZoom);document.getElementById('zoomIn')?.addEventListener('click',function(){if(currentZoom<5){currentZoom++;setZoom(currentZoom);}});document.getElementById('zoomOut')?.addEventListener('click',function(){if(currentZoom>1){currentZoom--;setZoom(currentZoom);}});document.getElementById('resetZoom')?.addEventListener('click',function(){currentZoom=2;setZoom(currentZoom);});document.getElementById('darkMode')?.addEventListener('click',function(){document.body.classList.add('dark-mode');localStorage.setItem('theme','dark');});document.getElementById('lightMode')?.addEventListener('click',function(){document.body.classList.remove('dark-mode');localStorage.setItem('theme','light');});if(localStorage.getItem('theme')==='dark'){document.body.classList.add('dark-mode');}
let translateLoaded=false;document.getElementById('translateBtn')?.addEventListener('click',function(){if(!translateLoaded){const oldTranslate=document.getElementById('google_translate_element');if(oldTranslate)oldTranslate.remove();const translateDiv=document.createElement('div');translateDiv.id='google_translate_element';translateDiv.style.position='fixed';translateDiv.style.top='100px';translateDiv.style.right='20px';translateDiv.style.zIndex='10001';translateDiv.style.background='white';translateDiv.style.padding='10px';translateDiv.style.borderRadius='8px';translateDiv.style.border='3px solid var(--gold)';translateDiv.style.boxShadow='0 10px 30px rgba(0,0,0,0.3)';document.body.appendChild(translateDiv);const script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';document.body.appendChild(script);window.googleTranslateElementInit=function(){new google.translate.TranslateElement({pageLanguage:'ar',includedLanguages:'ar,en,zh-CN,zh-TW,ja,ko',layout:google.translate.TranslateElement.InlineLayout.SIMPLE,autoDisplay:false},'google_translate_element');};translateLoaded=true;setTimeout(()=>{const closeBtn=document.createElement('span');closeBtn.innerHTML='&times;';closeBtn.style.position='absolute';closeBtn.style.top='5px';closeBtn.style.left='5px';closeBtn.style.fontSize='20px';closeBtn.style.cursor='pointer';closeBtn.style.color='var(--navy)';closeBtn.style.fontWeight='bold';closeBtn.onclick=function(){document.getElementById('google_translate_element').remove();translateLoaded=false;};document.getElementById('google_translate_element').appendChild(closeBtn);},1000);}else{document.getElementById('google_translate_element')?.remove();translateLoaded=false;}});
document.querySelectorAll('.faq-question').forEach(question=>{question.addEventListener('click',()=>{const faqItem=question.parentElement;faqItem.classList.toggle('active');document.querySelectorAll('.faq-item').forEach(item=>{if(item!==faqItem&&item.classList.contains('active')){item.classList.remove('active');}});});});
function showFieldError(elementId,message){const errorDiv=document.getElementById(elementId);if(errorDiv){errorDiv.textContent=message;errorDiv.classList.add('show');}}
function hideFieldError(elementId){const errorDiv=document.getElementById(elementId);if(errorDiv){errorDiv.classList.remove('show');}}
function hideAllErrors(prefix){const fields=[`${prefix}Name`,`${prefix}Phone`,`${prefix}Service`,`${prefix}Subject`,`${prefix}Type`];fields.forEach(field=>{const errorDiv=document.getElementById(field+'Error');if(errorDiv)errorDiv.classList.remove('show');});}
function showFormMessage(formId,type,text){const messageDiv=document.getElementById(formId+'FormMessage');if(messageDiv){messageDiv.className=`form-message ${type}`;messageDiv.textContent=text;messageDiv.style.display='block';setTimeout(()=>{messageDiv.style.display='none';},5000);}}
function playSuccessSound(){try{const audio=new Audio('sound/1.mp3');audio.volume=0.5;audio.play().catch(e=>console.log('ما في مشكلة'));}catch(e){console.log('الصوت ما اشتغل');}}
const bookingForm=document.getElementById('bookingForm');if(bookingForm){bookingForm.addEventListener('submit',function(e){e.preventDefault();hideAllErrors('booking');const name=document.getElementById('bookingName')?.value.trim();const phone=document.getElementById('bookingPhone')?.value.trim();const service=document.getElementById('bookingService')?.value;const message=document.getElementById('bookingMessage')?.value.trim();let hasError=false;if(!name){showFieldError('bookingNameError','الاسم مطلوب');hasError=true;}
if(!phone){showFieldError('bookingPhoneError','رقم الهاتف مطلوب');hasError=true;}else if(!/^\+?[0-9]+$/.test(phone)){showFieldError('bookingPhoneError','رقم الهاتف غير صحيح');hasError=true;}
if(!service){showFieldError('bookingServiceError','نوع الخدمة مطلوب');hasError=true;}
if(hasError)return;if(service==='حزمة مخصصة (إقامة طويلة)'&&!message){showFormMessage('booking','error','❌ للحزم المخصصة، يجب كتابة تفاصيل طلبك');return;}
playSuccessSound();if(!message){if(confirm('⚠️ لم تكتب رسالة. هل أنت متأكد أنك تريد الإرسال؟')){showFormMessage('booking','success','✅ تم إرسال طلب الحجز بنجاح! سنتواصل معك قريباً');bookingForm.reset();}}else{showFormMessage('booking','success','✅ تم إرسال طلب الحجز بنجاح! سنتواصل معك قريباً');bookingForm.reset();}});}
const inquiryForm=document.getElementById('inquiryForm');if(inquiryForm){inquiryForm.addEventListener('submit',function(e){e.preventDefault();hideAllErrors('inquiry');const name=document.getElementById('inquiryName')?.value.trim();const phone=document.getElementById('inquiryPhone')?.value.trim();const subject=document.getElementById('inquirySubject')?.value.trim();const message=document.getElementById('inquiryMessage')?.value.trim();let hasError=false;if(!name){showFieldError('inquiryNameError','الاسم مطلوب');hasError=true;}
if(!phone){showFieldError('inquiryPhoneError','رقم الهاتف مطلوب');hasError=true;}else if(!/^\+?[0-9]+$/.test(phone)){showFieldError('inquiryPhoneError','رقم الهاتف غير صحيح');hasError=true;}
if(!subject){showFieldError('inquirySubjectError','موضوع الاستفسار مطلوب');hasError=true;}
if(hasError)return;playSuccessSound();if(!message){if(confirm('⚠️ لم تكتب رسالة. هل أنت متأكد أنك تريد الإرسال؟')){showFormMessage('inquiry','success','✅ تم إرسال استفسارك بنجاح! سنرد عليك قريباً');inquiryForm.reset();}}else{showFormMessage('inquiry','success','✅ تم إرسال استفسارك بنجاح! سنرد عليك قريباً');inquiryForm.reset();}});}
const consultForm=document.getElementById('consultForm');if(consultForm){consultForm.addEventListener('submit',function(e){e.preventDefault();hideAllErrors('consult');const name=document.getElementById('consultName')?.value.trim();const phone=document.getElementById('consultPhone')?.value.trim();const type=document.getElementById('consultType')?.value;const message=document.getElementById('consultMessage')?.value.trim();let hasError=false;if(!name){showFieldError('consultNameError','الاسم مطلوب');hasError=true;}
if(!phone){showFieldError('consultPhoneError','رقم الهاتف مطلوب');hasError=true;}else if(!/^\+?[0-9]+$/.test(phone)){showFieldError('consultPhoneError','رقم الهاتف غير صحيح');hasError=true;}
if(!type){showFieldError('consultTypeError','نوع الاستشارة مطلوب');hasError=true;}
if(hasError)return;playSuccessSound();if(!message){if(confirm('⚠️ لم تكتب رسالة. هل أنت متأكد أنك تريد الإرسال؟')){showFormMessage('consult','success','✅ تم حجز استشارتك! سنحدد موعد معك قريباً');consultForm.reset();}}else{showFormMessage('consult','success','✅ تم حجز استشارتك! سنحدد موعد معك قريباً');consultForm.reset();}});}
const stars=document.querySelectorAll('.star');const ratingInput=document.getElementById('ratingValue');let selectedRating=0;if(stars.length>0){stars.forEach(star=>{star.addEventListener('click',function(){selectedRating=this.getAttribute('data-value');ratingInput.value=selectedRating;stars.forEach(s=>{if(s.getAttribute('data-value')<=selectedRating){s.classList.add('active');s.textContent='★';}else{s.classList.remove('active');s.textContent='☆';}});});star.addEventListener('mouseover',function(){const hoverValue=this.getAttribute('data-value');stars.forEach(s=>{if(s.getAttribute('data-value')<=hoverValue){s.style.color='var(--gold-light)';}});});star.addEventListener('mouseout',function(){stars.forEach(s=>{if(!s.classList.contains('active')){s.style.color='#ddd';}else{s.style.color='var(--gold)';}});});});}
function playHighRatingSound(){try{const audio=new Audio('sound/2.mp3');audio.volume=0.6;audio.play().catch(e=>console.log('ما في مشكلة'));}catch(e){console.log('الصوت ما اشتغل');}}
const ratingForm=document.getElementById('userRatingForm');if(ratingForm){ratingForm.addEventListener('submit',function(e){e.preventDefault();document.getElementById('ratingError')?.classList.remove('show');document.getElementById('ratingNameError')?.classList.remove('show');const rating=selectedRating;const name=document.getElementById('ratingName')?.value.trim();const comment=document.getElementById('ratingComment')?.value.trim();const formMessage=document.getElementById('ratingFormMessage');let hasError=false;if(!rating||rating==0){const errorDiv=document.getElementById('ratingError');if(errorDiv){errorDiv.textContent='يرجى اختيار تقييم';errorDiv.classList.add('show');}hasError=true;}
if(!name){const errorDiv=document.getElementById('ratingNameError');if(errorDiv){errorDiv.textContent='الاسم مطلوب';errorDiv.classList.add('show');}hasError=true;}
if(hasError)return;playHighRatingSound();formMessage.className='form-message success';formMessage.textContent='✅ شكراً لتقييمك! رأيك يهمنا';formMessage.style.display='block';ratingForm.reset();selectedRating=0;stars.forEach(s=>{s.classList.remove('active');s.textContent='☆';});setTimeout(()=>{formMessage.style.display='none';},4000);});
}